### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by projct1** [dangvanthanh/vue-clock#1]
http://joxi.ru/vAWYPzvHblVEmW
http://joxi.ru/Y2LqPzBu0qLgA6

**Comment by em7v** [comment]
It not npm module, it repository.

That do install the package, you must doing:
1. git clone this repository
2. npm install ( to folder with this repository )
3. npm run dev
( to folder with this repository )

**Comment by dangvanthanh** [comment]
Dear @projct1 

`vue-clock` was on npm but it isn't this repository. I will publish to npm with new name. 

@Friday14 Thank you very much when guide use this component.

**Comment by dangvanthanh** [comment]
Hi @Friday14
Hi @projct1 

I was publish component to npm

https://www.npmjs.com/package/@dangvanthanh/vue-clock

Thank you very much
