### ISSUE TITLE
Reactivity every second?

### ISSUE THREAD

**Issue by notflip** [dangvanthanh/vue-clock#2]
Just wondering, is it good practice to have a Vue data updated every second? So having reactivity every second? Just wondering if it'll be okay for performance in the long run.

**Comment by dangvanthanh** [comment]
Hi @notflip

I think if I use Observable that emits sequential numbers every specified interval of time of rxjs will be improve performance. I will test with it and update soon.

**Comment by dangvanthanh** [comment]
Hi @notflip 

I were improved performance in the long run by instead of `setInterval` with `setTimeout`
