### ISSUE TITLE
can i get just minutes and seconds and hourse and use

### ISSUE THREAD

**Issue by mohsenmehri6101** [dangvanthanh/vue-clock#6]
hi first thanks for this package
can i get just minutes and seconds and hourse and use ?

**Comment by dangvanthanh** [comment]
Hi @mohsenmehri6101 

I will upgrade to you can use configuration such as minutes, seconds and hours.

**Comment by dangvanthanh** [comment]
Hi @mohsenmehri6101 

I was update props for you can get hour, minute or second. See [example](https://github.com/dangvanthanh/vue-clock).
